package de.wwu.criticalsystems.libhpng.formulaparsing;
/* Generated By:JavaCC: Do not edit this line. SMCParserTreeConstants.java Version 6.0_1 */
public interface SMCParserTreeConstants
{
  public int JJTROOT = 0;
  public int JJTVOID = 1;
  public int JJTATOMIC = 2;
  public int JJTNOT = 3;
  public int JJTAND = 4;
  public int JJTOR = 5;
  public int JJTUNTIL = 6;
  public int JJTPROB = 7;
  public int JJTNUMBER = 8;
  public int JJTCOMPARE = 9;


  public String[] jjtNodeName = {
    "ROOT",
    "void",
    "ATOMIC",
    "NOT",
    "AND",
    "OR",
    "UNTIL",
    "PROB",
    "NUMBER",
    "COMPARE",
  };
}
/* JavaCC - OriginalChecksum=82c277918a5b6cb96a4d32f30fdcd5e9 (do not edit this line) */
