package de.wwu.criticalsystems.libhpng.formulaparsing;
/* Generated By:JJTree&JavaCC: Do not edit this line. SMCParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SMCParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LBRACE = 3;
  /** RegularExpression Id. */
  int RBRACE = 4;
  /** RegularExpression Id. */
  int LBRACESQ = 5;
  /** RegularExpression Id. */
  int RBRACESQ = 6;
  /** RegularExpression Id. */
  int COMPARE = 7;
  /** RegularExpression Id. */
  int DIGITS = 8;
  /** RegularExpression Id. */
  int NUMBER = 9;
  /** RegularExpression Id. */
  int ID = 10;
  /** RegularExpression Id. */
  int SEP = 11;
  /** RegularExpression Id. */
  int COLON = 12;
  /** RegularExpression Id. */
  int PROB = 13;
  /** RegularExpression Id. */
  int PROBQ = 14;
  /** RegularExpression Id. */
  int NOT = 15;
  /** RegularExpression Id. */
  int OR = 16;
  /** RegularExpression Id. */
  int AND = 17;
  /** RegularExpression Id. */
  int UNTIL = 18;
  /** RegularExpression Id. */
  int FLUID = 19;
  /** RegularExpression Id. */
  int TOKENS = 20;
  /** RegularExpression Id. */
  int ENABLED = 21;
  /** RegularExpression Id. */
  int CLOCK = 22;
  /** RegularExpression Id. */
  int FIRINGS = 23;
  /** RegularExpression Id. */
  int DRIFT = 24;
  /** RegularExpression Id. */
  int UBOUND = 25;
  /** RegularExpression Id. */
  int LBOUND = 26;
  /** RegularExpression Id. */
  int ARC = 27;
  /** RegularExpression Id. */
  int EOL = 28;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "<COMPARE>",
    "<DIGITS>",
    "<NUMBER>",
    "<ID>",
    "\",\"",
    "\":\"",
    "\"P\"",
    "\"P=?\"",
    "\"!\"",
    "\"OR\"",
    "\"AND\"",
    "\"U\"",
    "\"fluidlevel\"",
    "\"tokens\"",
    "\"enabled\"",
    "\"clock\"",
    "\"firings\"",
    "\"drift\"",
    "\"uboundary\"",
    "\"lboundary\"",
    "\"condition\"",
    "<EOL>",
  };

}
