package de.wwu.criticalsystems.libhpng.formulaparsing;
/* Generated By:JavaCC: Do not edit this line. SMCParserTreeConstants.java Version 6.0_1 */
public interface SMCParserTreeConstants
{
  public int JJTROOT = 0;
  public int JJTVOID = 1;
  public int JJTNOT = 2;
  public int JJTAND = 3;
  public int JJTOR = 4;
  public int JJTUNTIL = 5;
  public int JJTPROB = 6;
  public int JJTPROBQ = 7;
  public int JJTDOUBLE = 8;
  public int JJTINTEGER = 9;
  public int JJTCOMPARE = 10;
  public int JJTID = 11;
  public int JJTTIME = 12;
  public int JJTATOMIC_FLUID = 13;
  public int JJTATOMIC_TOKENS = 14;
  public int JJTATOMIC_ENABLED = 15;
  public int JJTATOMIC_CLOCK = 16;
  public int JJTATOMIC_FIRINGS = 17;
  public int JJTATOMIC_DRIFT = 18;
  public int JJTATOMIC_UBOUND = 19;
  public int JJTATOMIC_LBOUND = 20;
  public int JJTATOMIC_ARC = 21;


  public String[] jjtNodeName = {
    "ROOT",
    "void",
    "NOT",
    "AND",
    "OR",
    "UNTIL",
    "PROB",
    "PROBQ",
    "DOUBLE",
    "INTEGER",
    "COMPARE",
    "ID",
    "TIME",
    "ATOMIC_FLUID",
    "ATOMIC_TOKENS",
    "ATOMIC_ENABLED",
    "ATOMIC_CLOCK",
    "ATOMIC_FIRINGS",
    "ATOMIC_DRIFT",
    "ATOMIC_UBOUND",
    "ATOMIC_LBOUND",
    "ATOMIC_ARC",
  };
}
/* JavaCC - OriginalChecksum=18c4939f65e0cd912fdd7d45d0b90f4f (do not edit this line) */
