package de.wwu.criticalsystems.libhpng.formulaparsing;
/* Generated By:JavaCC: Do not edit this line. SMCParserTreeConstants.java Version 6.0_1 */
public interface SMCParserTreeConstants
{
  public int JJTROOT = 0;
  public int JJTVOID = 1;
  public int JJTNOT = 2;
  public int JJTAND = 3;
  public int JJTOR = 4;
  public int JJTUNTIL = 5;
  public int JJTPROBGE = 6;
  public int JJTPROBL = 7;
  public int JJTPROBQ = 8;
  public int JJTDOUBLE = 9;
  public int JJTINTEGER = 10;
  public int JJTCOMPARE = 11;
  public int JJTID = 12;
  public int JJTTIME = 13;
  public int JJTATOMIC_FLUID = 14;
  public int JJTATOMIC_TOKENS = 15;
  public int JJTATOMIC_ENABLED = 16;
  public int JJTATOMIC_CLOCK = 17;
  public int JJTATOMIC_FIRINGS = 18;
  public int JJTATOMIC_DRIFT = 19;
  public int JJTATOMIC_UBOUND = 20;
  public int JJTATOMIC_LBOUND = 21;
  public int JJTATOMIC_ARC = 22;
  public int JJTTRUE = 23;


  public String[] jjtNodeName = {
    "ROOT",
    "void",
    "NOT",
    "AND",
    "OR",
    "UNTIL",
    "PROBGE",
    "PROBL",
    "PROBQ",
    "DOUBLE",
    "INTEGER",
    "COMPARE",
    "ID",
    "TIME",
    "ATOMIC_FLUID",
    "ATOMIC_TOKENS",
    "ATOMIC_ENABLED",
    "ATOMIC_CLOCK",
    "ATOMIC_FIRINGS",
    "ATOMIC_DRIFT",
    "ATOMIC_UBOUND",
    "ATOMIC_LBOUND",
    "ATOMIC_ARC",
    "TRUE",
  };
}
/* JavaCC - OriginalChecksum=e621d627a69ad22bd2016ae3d61abe8a (do not edit this line) */
